---
- hosts: all
  become: true
  roles: [common]
- hosts: ops
  become: true
  roles: [ops]
- hosts: db
  become: true
  roles: [db]
- hosts: storage
  become: true
  roles: [garage]
- hosts: app
  become: true
  roles: [app]
- hosts: edge
  become: true
  roles: [edge]
