---
- hosts: all
  become: true
  roles: [common]
- hosts: ops
  become: true
  roles: [ops]
- hosts: observability
  become: true
  roles: [prometheus, loki, tempo, grafana, alertmanager, alloy]
- hosts: db
  become: true
  roles: [db, alloy]
- hosts: storage
  become: true
  roles: [garage, alloy]
- hosts: app
  become: true
  roles: [release_runtime, app, alloy]
- hosts: edge
  become: true
  roles: [release_runtime, edge, alloy]
