---
- hosts: all
  become: true
  roles: [common]
- hosts: ops
  become: true
  roles: [ops]
- hosts: observability
  become: true
  roles: [prometheus, loki, tempo]
- hosts: db
  become: true
  roles: [db]
- hosts: storage
  become: true
  roles: [garage]
- hosts: app
  become: true
  roles: [release_runtime, app]
- hosts: edge
  become: true
  roles: [release_runtime, edge]
