package com.siameselang.arp.integration;

import static org.assertj.core.api.Assertions.*;
import com.siameselang.arp.domain.*; import com.siameselang.arp.repository.*; import com.siameselang.arp.service.*; import com.siameselang.arp.storage.*;
import java.io.*; import java.nio.file.*; import java.security.*; import java.time.*; import java.util.HexFormat;
import org.junit.jupiter.api.*; import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.test.context.ActiveProfiles;

@SpringBootTest @ActiveProfiles("test") @EnabledIfEnvironmentVariable(named="GARAGE_INTEGRATION",matches="true")
class M3AttachmentGarageIntegrationTest {
 @Autowired AttachmentService service; @Autowired AttachmentTransactions tx; @Autowired AttachmentReconciliationService reconciliation; @Autowired ObjectStorage storage;
 @Autowired AttachmentRepository attachments; @Autowired ApplicationService applications; @Autowired UserRepository users; @Autowired ProgramRepository programs; @Autowired PasswordEncoder passwords;
 User owner,other,reviewer; Application application;
 @BeforeEach void setup(){attachments.deleteAll();owner=user("m3-owner",Role.APPLICANT);other=user("m3-other",Role.APPLICANT);reviewer=user("m3-reviewer",Role.REVIEWER);application=applications.create(owner,programs.findAll().getFirst().getId(),"Evidence","Body");}
 @Test void realGarageUploadVerifyDownloadAndDelete(){byte[] bytes="streamed evidence content".getBytes();Attachment a=service.upload(owner,application.getId(),"../proof.txt","text/plain",new ByteArrayInputStream(bytes));
  assertThat(a.getStatus()).isEqualTo(AttachmentStatus.AVAILABLE);assertThat(a.getObjectKey()).startsWith("application-review/attachments/").doesNotContain("proof.txt");assertThat(storage.exists(a.getObjectKey())).isTrue();assertThat(a.getSizeBytes()).isEqualTo(bytes.length);assertThat(a.getSha256()).isEqualTo(hash(bytes));
  try(var in=service.downloadForApplicant(owner,application.getId(),a.getId()).stream()){assertThat(in.readAllBytes()).isEqualTo(bytes);}catch(IOException e){throw new UncheckedIOException(e);}
  Attachment disposable=service.upload(owner,application.getId(),"delete.txt","text/plain",new ByteArrayInputStream("delete".getBytes()));service.delete(owner,application.getId(),disposable.getId());assertThat(attachments.findById(disposable.getId())).isEmpty();assertThat(storage.exists(disposable.getObjectKey())).isFalse();
  applications.submit(owner,application.getId());assertThat(service.listForReviewer(reviewer,application.getId())).contains(a);try(var in=service.downloadForReviewer(reviewer,application.getId(),a.getId()).stream()){assertThat(in.readAllBytes()).isEqualTo(bytes);}catch(IOException e){throw new UncheckedIOException(e);}}
 @Test void authorizationAndImmutableStateRejectMutationBeforeObjectWrite(){assertThatThrownBy(()->service.upload(other,application.getId(),"x","text/plain",new ByteArrayInputStream(new byte[]{1}))).isInstanceOf(BusinessRuleException.class);applications.submit(owner,application.getId());assertThatThrownBy(()->service.upload(owner,application.getId(),"x","text/plain",new ByteArrayInputStream(new byte[]{1}))).isInstanceOf(BusinessRuleException.class);assertThat(attachments.count()).isZero();assertThatThrownBy(()->service.listForApplicant(other,application.getId())).isInstanceOf(BusinessRuleException.class);assertThatThrownBy(()->service.delete(reviewer,application.getId(),999)).isInstanceOf(BusinessRuleException.class);}
 @Test void reconciliationRepairsPendingDetectsCorruptionMissingDeleteAndOrphanIdempotently()throws Exception {byte[] bytes="pending".getBytes();String pendingKey="application-review/attachments/"+application.getId()+"/pending";Attachment pending=tx.createPending(owner,application.getId(),pendingKey,"p.txt","text/plain",Instant.EPOCH);tx.recordFacts(pending.getId(),bytes.length,hash(bytes));put(pendingKey,bytes);
  String missingKey="application-review/attachments/"+application.getId()+"/missing";Attachment missing=tx.createPending(owner,application.getId(),missingKey,"m.txt","text/plain",Instant.EPOCH);
  Attachment corrupted=service.upload(owner,application.getId(),"c.txt","text/plain",new ByteArrayInputStream("good".getBytes()));put(corrupted.getObjectKey(),"bad".getBytes());Attachment availableMissing=service.upload(owner,application.getId(),"gone.txt","text/plain",new ByteArrayInputStream("gone".getBytes()));storage.delete(availableMissing.getObjectKey());
  Attachment deleting=service.upload(owner,application.getId(),"d.txt","text/plain",new ByteArrayInputStream("delete".getBytes()));tx.beginDelete(owner,application.getId(),deleting.getId());String orphan="application-review/attachments/orphan";put(orphan,"orphan".getBytes());
  var first=reconciliation.reconcile();assertThat(attachments.findById(pending.getId()).orElseThrow().getStatus()).isEqualTo(AttachmentStatus.AVAILABLE);assertThat(attachments.findById(missing.getId()).orElseThrow().getStatus()).isEqualTo(AttachmentStatus.FAILED);assertThat(attachments.findById(corrupted.getId()).orElseThrow().getStatus()).isEqualTo(AttachmentStatus.FAILED);assertThat(attachments.findById(availableMissing.getId()).orElseThrow().getStatus()).isEqualTo(AttachmentStatus.FAILED);assertThatThrownBy(()->service.downloadForApplicant(owner,application.getId(),availableMissing.getId())).isInstanceOf(ResourceNotFoundException.class);assertThat(attachments.findById(deleting.getId())).isEmpty();assertThat(first.orphanObjectKeys()).contains(orphan);assertThat(storage.exists(orphan)).isTrue();
  var second=reconciliation.reconcile();assertThat(second.madeAvailable()).isZero();assertThat(second.madeFailed()).isZero();assertThat(second.deleted()).isZero();assertThat(second.orphanObjectKeys()).contains(orphan);storage.delete(orphan);}
 private void put(String key,byte[] bytes)throws IOException{Path p=Files.createTempFile("garage-test-",".bin");try{Files.write(p,bytes);storage.put(key,p,bytes.length,"application/octet-stream");}finally{Files.deleteIfExists(p);}}
 private User user(String p,Role role){return users.save(new User(p+System.nanoTime(),passwords.encode("password"),role));}
 private static String hash(byte[] b){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
