---
timezone: Etc/UTC
app_private_ip: 10.40.0.20
db_private_ip: 10.40.0.30
garage_endpoint_ip: 10.40.0.41
garage_rpc_port: 3901
garage_s3_port: 3900
garage_replication_factor: 3
garage_image: dxflrs/garage:v2.4.1
garage_bucket: application-review
app_version: "{{ lookup('env', 'ARP_APP_VERSION') | default('m4-local', true) }}"
app_jar_source: "{{ lookup('env', 'ARP_APP_JAR') }}"
tls_certificate_source: "{{ lookup('env', 'ARP_TLS_CERTIFICATE') }}"
tls_private_key_source: "{{ lookup('env', 'ARP_TLS_PRIVATE_KEY') }}"
certbot_version: 5.8.0
opentofu_version: 1.12.6
opentofu_linux_amd64_sha256: 5dc43da4f750f33873dc25e94587128709e819e544b7be9016b255316153c3a8
sops_version: 3.10.2
sops_linux_amd64_sha256: 79b0f844237bd4b0446e4dc884dbc1765fc7dedc3968f743d5949c6f2e701739
observability_private_ip: 10.40.0.60
prometheus_version: 3.13.3
prometheus_linux_amd64_sha256: b349c732d8a853e657d0e7ae1bbad4d11b586615fb65fdc59d896b9f869c001e
prometheus_retention_time: 3d
prometheus_retention_size: 12GB
loki_image: grafana/loki:3.7.7
loki_memory_limit: 1g
loki_cpu_limit: 1.0
tempo_image: grafana/tempo:3.0.2
tempo_memory_limit: 1536m
tempo_cpu_limit: 1.0
