import { FormEvent, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, ApiError } from '../api/client'
import { ErrorNotice } from '../components/ErrorNotice'
import { StatusBadge } from '../components/StatusBadge'
import { formatMoney } from './ApplicationsPage'
import { applicationStatusLabel, applicationStatusLabels, auditEventLabels, formatDateTime, intakeStatusLabels, publicationStatusLabels, roleLabels } from '../utils/presentation'
import type { AdminApplicationDetail, AdminAuditItem, AdminHistoryItem, AdminProgram, AdminWorkflowCounts, ApiPage, ApplicationStatus, AuditEventType, Role, AdminUserSummary, AdminApplicationSummary } from '../types/api'

const statuses: ApplicationStatus[] = ['DRAFT', 'SUBMITTED', 'IN_REVIEW', 'NEEDS_REVISION', 'APPROVED', 'REJECTED']
const events: AuditEventType[] = ['APPLICATION_CREATED','APPLICATION_EDITED','APPLICATION_SUBMITTED','REVIEW_STARTED','REVISION_REQUESTED','APPLICATION_APPROVED','APPLICATION_REJECTED','USER_REGISTERED','PROGRAM_CREATED','PROGRAM_UPDATED','PROGRAM_PUBLISHED']
const date = formatDateTime

function PageNav({ page, setPage }: { page: ApiPage<unknown>; setPage: (page: number) => void }) {
  return <div className="pagination"><button className="button secondary" disabled={page.page === 0} onClick={() => setPage(page.page - 1)}>이전</button><span>{page.page + 1} / {Math.max(page.totalPages, 1)}쪽 · 전체 {page.totalElements}개</span><button className="button secondary" disabled={page.page + 1 >= page.totalPages} onClick={() => setPage(page.page + 1)}>다음</button></div>
}

export function AdminDashboardPage() {
  const [counts, setCounts] = useState<AdminWorkflowCounts>(); const [error, setError] = useState<unknown>()
  useEffect(() => { api.adminWorkflowCounts().then(setCounts).catch(setError) }, [])
  const values = counts && [['전체 신청', counts.total], ['작성 중', counts.draft], ['제출 완료', counts.submitted], ['심사 중', counts.inReview], ['보완 요청', counts.needsRevision], ['승인', counts.approved], ['반려', counts.rejected]] as const
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">관리자 업무</p><h1>운영 현황</h1><p>신청 진행 현황을 확인하고 각 관리 업무로 이동하세요.</p></div></div>{error !== undefined && <ErrorNotice error={error}/>} {!counts && !error && <div className="notice">운영 현황을 불러오는 중…</div>}{values && <div className="summary-grid">{values.map(([label, value]) => <div className="summary-card" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>}<div className="card-grid">{[['지원사업','지원사업을 작성·수정하고 게시합니다.','/admin/programs'],['신청 관리','신청 내용과 진행 이력을 조회합니다.','/admin/applications'],['사용자 관리','역할별 등록 사용자를 조회합니다.','/admin/users'],['감사 기록','주요 업무 처리 기록을 조회합니다.','/admin/audits']].map(([title, copy, to]) => <Link className="card" to={to} key={to}><h2>{title}</h2><p>{copy}</p></Link>)}</div></section>
}

export function AdminProgramsPage() {
  const [number, setNumber] = useState(0); const [page, setPage] = useState<ApiPage<AdminProgram>>(); const [error, setError] = useState<unknown>()
  useEffect(() => { setError(undefined); api.adminPrograms(number).then(setPage).catch(setError) }, [number])
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">관리자 업무</p><h1>지원사업</h1></div><Link className="button" to="/admin/programs/new">새 사업 작성</Link></div>{error !== undefined && <ErrorNotice error={error}/>} {page && <><div className="table-wrap"><table><thead><tr><th>사업 코드</th><th>사업명</th><th>게시 상태</th><th>접수 상태</th><th>수정일</th><th/></tr></thead><tbody>{page.items.map(p => <tr key={p.id}><td>{p.code}</td><td>{p.title}</td><td><span className={`status status-${p.publicationStatus.toLowerCase()}`}>{publicationStatusLabels[p.publicationStatus]}</span></td><td>{p.intakeStatus ? intakeStatusLabels[p.intakeStatus] : '미게시'}</td><td>{date(p.updatedAt)}</td><td><Link to={`/admin/programs/${p.id}`}>상세 보기</Link></td></tr>)}</tbody></table></div>{page.items.length === 0 && <div className="notice">등록된 지원사업이 없습니다.</div>}<PageNav page={page} setPage={setNumber}/></>}{!page && !error && <div className="notice">지원사업을 불러오는 중…</div>}</section>
}

export function AdminProgramDetailPage() {
  const { programId } = useParams(); const [program, setProgram] = useState<AdminProgram>(); const [error, setError] = useState<unknown>(); const [publishing, setPublishing] = useState(false); const load = () => { if (!programId) return; setError(undefined); api.adminProgram(programId).then(setProgram).catch(setError) }
  useEffect(() => { load() }, [programId])
  async function publish() { if (!program || !window.confirm('Publish this program? Publishing cannot be undone in this workflow.')) return; setPublishing(true); setError(undefined); try { setProgram(await api.publishAdminProgram(program.id, program.version)) } catch (e) { setError(e) } finally { setPublishing(false) } }
  return <section className="page"><Link to="/admin/programs">← 지원사업 목록</Link>{error !== undefined && <><ErrorNotice error={error}/>{error instanceof ApiError && error.status === 409 && <button className="button secondary" onClick={load}>최신 사업 정보 불러오기</button>}</>}{!program && !error && <div className="notice">지원사업을 불러오는 중…</div>}{program && <><div className="page-heading"><div><p className="eyebrow">{program.code}</p><h1>{program.title}</h1></div>{program.publicationStatus === 'DRAFT' && <div className="actions"><Link className="button secondary" to={`/admin/programs/${program.id}/edit`}>수정</Link><button className="button" disabled={publishing} onClick={publish}>{publishing ? '게시 중…' : '지원사업 게시'}</button></div>}</div><div className="detail-grid"><div><dt>게시 상태</dt><dd><span className={`status status-${program.publicationStatus.toLowerCase()}`}>{publicationStatusLabels[program.publicationStatus]}</span></dd></div><div><dt>접수 상태</dt><dd>{program.intakeStatus ? intakeStatusLabels[program.intakeStatus] : '작성 중인 사업은 접수 상태가 없습니다'}</dd></div><div><dt>접수 시작</dt><dd>{date(program.applicationOpenAt)}</dd></div><div><dt>접수 마감</dt><dd>{date(program.applicationCloseAt)}</dd></div></div><article className="content-card"><h2>사업 설명</h2><p className="preserve-lines">{program.description}</p></article></>}</section>
}

function local(instant: string) { const d = new Date(instant); const offset = d.getTimezoneOffset(); return new Date(d.getTime() - offset * 60000).toISOString().slice(0, 16) }
export function AdminProgramFormPage({ edit = false }: { edit?: boolean }) {
  const { programId } = useParams(); const navigate = useNavigate(); const [version, setVersion] = useState(0); const [code, setCode] = useState(''); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [open, setOpen] = useState(''); const [close, setClose] = useState(''); const [error, setError] = useState<unknown>(); const [validation, setValidation] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { if (edit && programId) api.adminProgram(programId).then(p => { if (p.publicationStatus !== 'DRAFT') throw new Error('Published programs are read-only.'); setVersion(p.version); setCode(p.code); setTitle(p.title); setDescription(p.description); setOpen(local(p.applicationOpenAt)); setClose(local(p.applicationCloseAt)) }).catch(setError) }, [edit, programId])
  async function submit(e: FormEvent) { e.preventDefault(); setValidation(''); setError(undefined); if (!title.trim() || !description.trim() || !open || !close || (!edit && !/^[A-Za-z0-9][A-Za-z0-9_-]{1,49}$/.test(code.trim()))) return setValidation('Complete all fields with a valid 2–50 character program code.'); if (title.length > 255 || description.length > 4000 || new Date(open) >= new Date(close)) return setValidation('Check field lengths and ensure the opening time is before the closing time.'); setSaving(true); try { const times = { title: title.trim(), description: description.trim(), applicationOpenAt: new Date(open).toISOString(), applicationCloseAt: new Date(close).toISOString() }; const saved = edit && programId ? await api.updateAdminProgram(programId, { version, ...times }) : await api.createAdminProgram({ code: code.trim(), ...times }); navigate(`/admin/programs/${saved.id}`) } catch (e) { setError(e) } finally { setSaving(false) } }
  const formReady = !edit || code !== ''
  return <section className="page narrow"><Link to={programId ? `/admin/programs/${programId}` : '/admin/programs'}>← 취소</Link><div className="page-heading"><div><p className="eyebrow">관리자 업무</p><h1>{edit ? '지원사업 초안 수정' : '지원사업 초안 작성'}</h1></div></div>{error !== undefined && <><ErrorNotice error={error}/>{error instanceof ApiError && error.status === 409 && programId && <Link to={`/admin/programs/${programId}`}>최신 사업 정보로 돌아가기</Link>}</>}{edit && !formReady && error === undefined && <div className="notice" role="status">지원사업 초안을 불러오는 중…</div>}{validation && <div className="notice error" role="alert">{validation}</div>}{formReady && <form className="business-form" onSubmit={submit}>{edit ? <label>사업 코드<input value={code} disabled aria-describedby="immutable-code"/><small id="immutable-code">사업 코드는 변경할 수 없습니다.</small></label> : <label>사업 코드<input value={code} onChange={e => setCode(e.target.value)} maxLength={50} required/></label>}<label>사업명<input value={title} onChange={e => setTitle(e.target.value)} maxLength={255} required/></label><label>사업 설명<textarea value={description} onChange={e => setDescription(e.target.value)} maxLength={4000} required rows={8}/></label><div className="form-row"><label>접수 시작<input type="datetime-local" value={open} onChange={e => setOpen(e.target.value)} required/></label><label>접수 마감<input type="datetime-local" value={close} onChange={e => setClose(e.target.value)} required/></label></div><button className="button" disabled={saving}>{saving ? '저장 중…' : edit ? '초안 저장' : '초안 만들기'}</button></form>}</section>
}

export function AdminUsersPage() { const [number,setNumber]=useState(0), [role,setRole]=useState<Role|''>(''); const [page,setPage]=useState<ApiPage<AdminUserSummary>>(); const [error,setError]=useState<unknown>(); useEffect(()=>{api.adminUsers(number,20,role||undefined).then(setPage).catch(setError)},[number,role]); return <section className="page"><h1>사용자 관리</h1><label className="filter">역할<select value={role} onChange={e=>{setRole(e.target.value as Role|'');setNumber(0)}}><option value="">전체 역할</option><option>APPLICANT</option><option>REVIEWER</option><option>ADMIN</option></select></label>{error!==undefined&&<ErrorNotice error={error}/>} {page&&<><div className="table-wrap"><table><thead><tr><th>아이디</th><th>이름</th><th>이메일</th><th>역할</th><th>가입일</th></tr></thead><tbody>{page.items.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.displayName}</td><td>{u.email}</td><td>{roleLabels[u.role]}</td><td>{date(u.createdAt)}</td></tr>)}</tbody></table></div><PageNav page={page} setPage={setNumber}/></>}</section> }

export function AdminApplicationsPage() { const [number,setNumber]=useState(0),[status,setStatus]=useState<ApplicationStatus|''>('');const[page,setPage]=useState<ApiPage<AdminApplicationSummary>>();const[error,setError]=useState<unknown>();useEffect(()=>{api.adminApplications(number,20,status||undefined).then(setPage).catch(setError)},[number,status]);return <section className="page"><h1>신청 관리</h1><label className="filter">진행 상태<select value={status} onChange={e=>{setStatus(e.target.value as ApplicationStatus|'');setNumber(0)}}><option value="">전체 상태</option>{statuses.map(s=><option key={s} value={s}>{applicationStatusLabels[s]}</option>)}</select></label>{error!==undefined&&<ErrorNotice error={error}/>} {page&&<><div className="table-wrap"><table><thead><tr><th>지원사업</th><th>신청 기관 / 과제</th><th>신청자</th><th>심사자</th><th>신청 금액</th><th>진행 상태</th><th>수정일</th><th/></tr></thead><tbody>{page.items.map(a=><tr key={a.id}><td>{a.program.code}</td><td>{a.applicantOrganizationName}<br/><small>{a.projectTitle}</small></td><td>{a.applicant.displayName}</td><td>{a.reviewer?.displayName??'미배정'}</td><td>{formatMoney(a.requestedAmount)}</td><td><StatusBadge status={a.status}/></td><td>{date(a.updatedAt)}</td><td><Link to={`/admin/applications/${a.id}`}>상세 보기</Link></td></tr>)}</tbody></table></div><PageNav page={page} setPage={setNumber}/></>}</section> }

export function AdminApplicationDetailPage() { const {applicationId}=useParams();const[application,setApplication]=useState<AdminApplicationDetail>();const[history,setHistory]=useState<AdminHistoryItem[]>([]);const[error,setError]=useState<unknown>();useEffect(()=>{if(applicationId)Promise.all([api.adminApplication(applicationId),api.adminApplicationHistory(applicationId)]).then(([a,h])=>{setApplication(a);setHistory(h)}).catch(setError)},[applicationId]);return <section className="page"><Link to="/admin/applications">← 신청 관리</Link>{error!==undefined&&<ErrorNotice error={error}/>} {application&&<><div className="page-heading"><div><p className="eyebrow">{application.program.code}</p><h1>{application.projectTitle}</h1><StatusBadge status={application.status}/></div></div><div className="detail-grid"><div><dt>신청 기관</dt><dd>{application.applicantOrganizationName}</dd></div><div><dt>신청자</dt><dd>{application.applicant.displayName} ({application.applicant.username})</dd></div><div><dt>심사자</dt><dd>{application.reviewer?.displayName??'미배정'}</dd></div><div><dt>신청 금액</dt><dd>{formatMoney(application.requestedAmount)}</dd></div></div><article className="content-card"><h2>요약</h2><p>{application.shortSummary}</p><h2>세부 계획</h2><p className="preserve-lines">{application.detailedPlan}</p></article><section><h2>진행 이력</h2>{history.length===0?<div className="notice">기록된 진행 이력이 없습니다.</div>:<ol className="history-list">{history.map(h=><li key={h.id}><strong>{h.fromStatus ? applicationStatusLabel(h.fromStatus) : '신청서 작성'} → {applicationStatusLabel(h.toStatus)}</strong><span>{date(h.changedAt)} · {h.changedBy.displayName} ({roleLabels[h.changedBy.role]})</span>{h.reason&&<p>{h.reason}</p>}</li>)}</ol>}</section></>}</section> }

function Subject({audit}:{audit:AdminAuditItem}) { const label=`${audit.subjectType} #${audit.subjectId}`; if(audit.subjectType==='APPLICATION')return <Link to={`/admin/applications/${audit.subjectId}`}>{label}</Link>;if(audit.subjectType==='PROGRAM')return <Link to={`/admin/programs/${audit.subjectId}`}>{label}</Link>;return <span>{label}</span> }
export function AdminAuditsPage() { const[number,setNumber]=useState(0),[event,setEvent]=useState<AuditEventType|''>('');const[page,setPage]=useState<ApiPage<AdminAuditItem>>();const[error,setError]=useState<unknown>();useEffect(()=>{api.adminAudits(number,50,event||undefined).then(setPage).catch(setError)},[number,event]);return <section className="page"><h1>감사 기록</h1><label className="filter">이벤트 유형<select value={event} onChange={e=>{setEvent(e.target.value as AuditEventType|'');setNumber(0)}}><option value="">전체 이벤트</option>{events.map(e=><option key={e} value={e}>{auditEventLabels[e]}</option>)}</select></label>{error!==undefined&&<ErrorNotice error={error}/>} {page&&<><div className="table-wrap"><table><thead><tr><th>처리 시각</th><th>이벤트</th><th>처리자</th><th>대상</th></tr></thead><tbody>{page.items.map(a=><tr key={a.id}><td>{date(a.occurredAt)}</td><td>{auditEventLabels[a.eventType]}</td><td>{a.actor.displayName} ({roleLabels[a.actor.role]})</td><td><Subject audit={a}/></td></tr>)}</tbody></table></div><PageNav page={page} setPage={setNumber}/></>}</section> }
