import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { clearCsrfTokenForTests } from '../api/client'
import { AdminApplicationDetailPage, AdminApplicationsPage, AdminAuditsPage, AdminDashboardPage, AdminProgramDetailPage, AdminProgramFormPage, AdminUsersPage } from './AdminPages'

const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }))
const page = (items: unknown[]) => ({ items, page: 0, size: 20, totalElements: items.length, totalPages: 1 })
const program = (publicationStatus: 'DRAFT'|'PUBLISHED' = 'DRAFT') => ({ id: 4, version: 3, code: 'PROGRAM-2026', title: 'Program title', description: 'Program description', publicationStatus, applicationOpenAt: '2026-10-01T00:00:00Z', applicationCloseAt: '2026-11-01T00:00:00Z', intakeStatus: publicationStatus === 'PUBLISHED' ? 'SCHEDULED' : null, createdAt: '2026-09-01T00:00:00Z', updatedAt: '2026-09-02T00:00:00Z' })
afterEach(() => { cleanup(); clearCsrfTokenForTests(); vi.unstubAllGlobals(); vi.restoreAllMocks() })

describe('admin product surface', () => {
  it('renders workflow counts and operational destinations', async () => { vi.stubGlobal('fetch', vi.fn(() => json({ total: 7, draft: 1, submitted: 2, inReview: 1, needsRevision: 1, approved: 1, rejected: 1 }))); render(<MemoryRouter><AdminDashboardPage/></MemoryRouter>); expect(await screen.findByText('7')).toBeInTheDocument(); expect(screen.getByText('전체 신청')).toBeInTheDocument(); expect(screen.getByRole('link', { name: /감사 기록/ })).toBeInTheDocument() })

  it.each([['DRAFT', true], ['PUBLISHED', false]] as const)('shows mutation controls only for a %s program', async (status, mutable) => { vi.stubGlobal('fetch', vi.fn(() => json(program(status)))); render(<MemoryRouter initialEntries={['/admin/programs/4']}><Routes><Route path="/admin/programs/:programId" element={<AdminProgramDetailPage/>}/></Routes></MemoryRouter>); await screen.findByRole('heading', { name: 'Program title' }); expect(screen.queryByRole('link', { name: '수정' }) !== null).toBe(mutable); expect(screen.queryByRole('button', { name: '지원사업 게시' }) !== null).toBe(mutable) })

  it('publishes with the current version and removes mutation controls', async () => { const fetch = vi.fn((url: string, init?: RequestInit) => { if (url === '/api/v1/auth/csrf') return json({ headerName: 'X-CSRF-TOKEN', parameterName: '_csrf', token: 'token' }); if (init?.method === 'POST') { expect(JSON.parse(String(init.body))).toEqual({ version: 3 }); return json(program('PUBLISHED')) } return json(program()) }); vi.stubGlobal('fetch', fetch); vi.stubGlobal('confirm', () => true); render(<MemoryRouter initialEntries={['/admin/programs/4']}><Routes><Route path="/admin/programs/:programId" element={<AdminProgramDetailPage/>}/></Routes></MemoryRouter>); fireEvent.click(await screen.findByRole('button', { name: '지원사업 게시' })); await screen.findByText('접수 예정'); expect(screen.queryByRole('button', { name: '지원사업 게시' })).not.toBeInTheDocument(); expect(fetch).toHaveBeenCalledTimes(3) })

  it('creates with code and ISO instants and validates the window', async () => { const fetch = vi.fn((url: string, init?: RequestInit) => { if (url.endsWith('/csrf')) return json({ headerName: 'X-CSRF-TOKEN', parameterName: '_csrf', token: 'token' }); const body = JSON.parse(String(init?.body)); expect(body.code).toBe('PROGRAM-2026'); expect(body.applicationOpenAt).toMatch(/Z$/); expect(body.applicationCloseAt).toMatch(/Z$/); return json(program(), 201) }); vi.stubGlobal('fetch', fetch); render(<MemoryRouter initialEntries={['/admin/programs/new']}><Routes><Route path="/admin/programs/new" element={<AdminProgramFormPage/>}/><Route path="/admin/programs/4" element={<h1>Saved</h1>}/></Routes></MemoryRouter>); fireEvent.change(screen.getByLabelText('사업 코드'), { target: { value: 'PROGRAM-2026' } }); fireEvent.change(screen.getByLabelText('사업명'), { target: { value: '사업명' } }); fireEvent.change(screen.getByLabelText('사업 설명'), { target: { value: '사업 설명' } }); fireEvent.change(screen.getByLabelText('접수 시작'), { target: { value: '2026-11-01T10:00' } }); fireEvent.change(screen.getByLabelText('접수 마감'), { target: { value: '2026-10-01T10:00' } }); fireEvent.click(screen.getByRole('button', { name: '초안 만들기' })); expect(await screen.findByRole('alert')).toHaveTextContent('접수 시작 일시가 마감 일시보다 빠른지'); expect(fetch).not.toHaveBeenCalled(); fireEvent.change(screen.getByLabelText('접수 마감'), { target: { value: '2026-12-01T10:00' } }); fireEvent.click(screen.getByRole('button', { name: '초안 만들기' })); expect(await screen.findByRole('heading', { name: 'Saved' })).toBeInTheDocument() })

  it('does not render an edit form when a published program edit route is opened directly', async () => { vi.stubGlobal('fetch', vi.fn(() => json(program('PUBLISHED')))); render(<MemoryRouter initialEntries={['/admin/programs/4/edit']}><Routes><Route path="/admin/programs/:programId/edit" element={<AdminProgramFormPage edit/>}/></Routes></MemoryRouter>); expect(await screen.findByRole('alert')).toHaveTextContent('게시 완료된 지원사업은 수정할 수 없습니다'); expect(screen.queryByRole('button', { name: '초안 저장' })).not.toBeInTheDocument(); expect(screen.queryByDisplayValue('PROGRAM-2026')).not.toBeInTheDocument() })

  it('edits with version, excludes code, and exposes conflict recovery without retry', async () => { const fetch = vi.fn((url: string, init?: RequestInit) => { if (url.endsWith('/csrf')) return json({ headerName: 'X-CSRF-TOKEN', parameterName: '_csrf', token: 'token' }); if (init?.method === 'PUT') { const body = JSON.parse(String(init.body)); expect(body.version).toBe(3); expect(body).not.toHaveProperty('code'); return json({ title: 'Conflict', status: 409, detail: 'Program was modified by another request' }, 409) } return json(program()) }); vi.stubGlobal('fetch', fetch); render(<MemoryRouter initialEntries={['/admin/programs/4/edit']}><Routes><Route path="/admin/programs/:programId/edit" element={<AdminProgramFormPage edit/>}/></Routes></MemoryRouter>); await screen.findByDisplayValue('Program title'); expect(screen.getByDisplayValue('PROGRAM-2026')).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: '초안 저장' })); expect(await screen.findByRole('alert')).toHaveTextContent('modified'); expect(screen.getByRole('link', { name: '최신 사업 정보로 돌아가기' })).toBeInTheDocument(); expect(fetch).toHaveBeenCalledTimes(3) })

  it('requests user role, application status, and audit event filters', async () => { const fetch = vi.fn(() => json(page([]))); vi.stubGlobal('fetch', fetch); const { unmount } = render(<MemoryRouter><AdminUsersPage/></MemoryRouter>); await waitFor(() => expect(fetch).toHaveBeenCalled()); fireEvent.change(screen.getByLabelText('역할'), { target: { value: 'ADMIN' } }); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('role=ADMIN'), expect.anything())); unmount(); render(<MemoryRouter><AdminApplicationsPage/></MemoryRouter>); fireEvent.change(screen.getByLabelText('진행 상태'), { target: { value: 'APPROVED' } }); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('status=APPROVED'), expect.anything())); cleanup(); render(<MemoryRouter><AdminAuditsPage/></MemoryRouter>); fireEvent.change(screen.getByLabelText('이벤트 유형'), { target: { value: 'PROGRAM_PUBLISHED' } }); await waitFor(() => expect(fetch).toHaveBeenCalledWith(expect.stringContaining('eventType=PROGRAM_PUBLISHED'), expect.anything())); expect(screen.queryByText(/passwordHash/i)).not.toBeInTheDocument() })

  it('links application and program audit subjects but leaves users as text', async () => { const actor = { id: 1, username: 'admin', displayName: 'Administrator', role: 'ADMIN' }; vi.stubGlobal('fetch', vi.fn(() => json(page([{ id: 1, eventType: 'APPLICATION_CREATED', occurredAt: '2026-01-01T00:00:00Z', actor, subjectType: 'APPLICATION', subjectId: 8 }, { id: 2, eventType: 'PROGRAM_CREATED', occurredAt: '2026-01-01T00:00:00Z', actor, subjectType: 'PROGRAM', subjectId: 4 }, { id: 3, eventType: 'USER_REGISTERED', occurredAt: '2026-01-01T00:00:00Z', actor, subjectType: 'USER', subjectId: 2 }])))); render(<MemoryRouter><AdminAuditsPage/></MemoryRouter>); expect(await screen.findByRole('link', { name: '신청서 #8' })).toHaveAttribute('href', '/admin/applications/8'); expect(screen.getByRole('link', { name: '지원사업 #4' })).toHaveAttribute('href', '/admin/programs/4'); expect(screen.getByText('사용자 #2').closest('a')).toBeNull() })

  it('renders full read-only application detail and actor history', async () => { const detail = { id: 8, program: { id: 4, code: 'PROGRAM-2026', title: 'Program title' }, applicant: { id: 2, username: 'applicant', displayName: 'Applicant', role: 'APPLICANT' }, reviewer: null, applicantOrganizationName: 'Synthetic Org', projectTitle: 'Project', shortSummary: 'Full summary', requestedAmount: 2000, detailedPlan: 'Full detailed plan', status: 'SUBMITTED', version: 2, createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-02T00:00:00Z' }; vi.stubGlobal('fetch', vi.fn((url:string) => url.endsWith('/history') ? json([{ id: 1, changedAt: detail.updatedAt, fromStatus: 'DRAFT', toStatus: 'SUBMITTED', changedBy: { id: 2, username: 'applicant', displayName: 'Applicant', role: 'APPLICANT' }, reason: 'Ready for review' }]) : json(detail))); render(<MemoryRouter initialEntries={['/admin/applications/8']}><Routes><Route path="/admin/applications/:applicationId" element={<AdminApplicationDetailPage/>}/></Routes></MemoryRouter>); expect(await screen.findByText('Full detailed plan')).toBeInTheDocument(); expect(screen.getByText(/Applicant \(신청자\)/)).toBeInTheDocument(); expect(screen.getByText('Ready for review')).toBeInTheDocument(); expect(screen.queryByRole('button')).not.toBeInTheDocument() })
})
