import { FormEvent, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, ApiError } from '../api/client'
import { ErrorNotice } from '../components/ErrorNotice'
import { StatusBadge } from '../components/StatusBadge'
import { formatMoney } from './ApplicationsPage'
import type { AdminApplicationDetail, AdminAuditItem, AdminHistoryItem, AdminProgram, AdminWorkflowCounts, ApiPage, ApplicationStatus, AuditEventType, Role, AdminUserSummary, AdminApplicationSummary } from '../types/api'

const statuses: ApplicationStatus[] = ['DRAFT', 'SUBMITTED', 'IN_REVIEW', 'NEEDS_REVISION', 'APPROVED', 'REJECTED']
const events: AuditEventType[] = ['APPLICATION_CREATED','APPLICATION_EDITED','APPLICATION_SUBMITTED','REVIEW_STARTED','REVISION_REQUESTED','APPLICATION_APPROVED','APPLICATION_REJECTED','USER_REGISTERED','PROGRAM_CREATED','PROGRAM_UPDATED','PROGRAM_PUBLISHED']
const date = (value: string) => new Date(value).toLocaleString()

function PageNav({ page, setPage }: { page: ApiPage<unknown>; setPage: (page: number) => void }) {
  return <div className="pagination"><button className="button secondary" disabled={page.page === 0} onClick={() => setPage(page.page - 1)}>Previous</button><span>Page {page.page + 1} of {Math.max(page.totalPages, 1)} · {page.totalElements} total</span><button className="button secondary" disabled={page.page + 1 >= page.totalPages} onClick={() => setPage(page.page + 1)}>Next</button></div>
}

export function AdminDashboardPage() {
  const [counts, setCounts] = useState<AdminWorkflowCounts>(); const [error, setError] = useState<unknown>()
  useEffect(() => { api.adminWorkflowCounts().then(setCounts).catch(setError) }, [])
  const values = counts && [['Total applications', counts.total], ['Draft', counts.draft], ['Submitted', counts.submitted], ['In review', counts.inReview], ['Needs revision', counts.needsRevision], ['Approved', counts.approved], ['Rejected', counts.rejected]] as const
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">Administration</p><h1>Operational overview</h1><p>Current workflow counts and read-only operational access.</p></div></div>{error !== undefined && <ErrorNotice error={error}/>} {!counts && !error && <div className="notice">Loading workflow counts…</div>}{values && <div className="summary-grid">{values.map(([label, value]) => <div className="summary-card" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>}<div className="card-grid">{[['Programs','Create, update, and publish program drafts.','/admin/programs'],['Applications','Inspect applications and status history.','/admin/applications'],['Users','Inspect registered users by role.','/admin/users'],['Audit events','Inspect recorded business events.','/admin/audits']].map(([title, copy, to]) => <Link className="card" to={to} key={to}><h2>{title}</h2><p>{copy}</p></Link>)}</div></section>
}

export function AdminProgramsPage() {
  const [number, setNumber] = useState(0); const [page, setPage] = useState<ApiPage<AdminProgram>>(); const [error, setError] = useState<unknown>()
  useEffect(() => { setError(undefined); api.adminPrograms(number).then(setPage).catch(setError) }, [number])
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">Administration</p><h1>Programs</h1></div><Link className="button" to="/admin/programs/new">Create draft</Link></div>{error !== undefined && <ErrorNotice error={error}/>} {page && <><div className="table-wrap"><table><thead><tr><th>Code</th><th>Title</th><th>Publication</th><th>Intake</th><th>Updated</th><th/></tr></thead><tbody>{page.items.map(p => <tr key={p.id}><td>{p.code}</td><td>{p.title}</td><td><span className={`status status-${p.publicationStatus.toLowerCase()}`}>{p.publicationStatus === 'DRAFT' ? 'Draft' : 'Published'}</span></td><td>{p.intakeStatus ?? 'Not published'}</td><td>{date(p.updatedAt)}</td><td><Link to={`/admin/programs/${p.id}`}>View</Link></td></tr>)}</tbody></table></div>{page.items.length === 0 && <div className="notice">No programs found.</div>}<PageNav page={page} setPage={setNumber}/></>}{!page && !error && <div className="notice">Loading programs…</div>}</section>
}

export function AdminProgramDetailPage() {
  const { programId } = useParams(); const [program, setProgram] = useState<AdminProgram>(); const [error, setError] = useState<unknown>(); const [publishing, setPublishing] = useState(false); const load = () => { if (!programId) return; setError(undefined); api.adminProgram(programId).then(setProgram).catch(setError) }
  useEffect(() => { load() }, [programId])
  async function publish() { if (!program || !window.confirm('Publish this program? Publishing cannot be undone in this workflow.')) return; setPublishing(true); setError(undefined); try { setProgram(await api.publishAdminProgram(program.id, program.version)) } catch (e) { setError(e) } finally { setPublishing(false) } }
  return <section className="page"><Link to="/admin/programs">← Programs</Link>{error !== undefined && <><ErrorNotice error={error}/>{error instanceof ApiError && error.status === 409 && <button className="button secondary" onClick={load}>Reload latest program</button>}</>}{!program && !error && <div className="notice">Loading program…</div>}{program && <><div className="page-heading"><div><p className="eyebrow">{program.code}</p><h1>{program.title}</h1></div>{program.publicationStatus === 'DRAFT' && <div className="actions"><Link className="button secondary" to={`/admin/programs/${program.id}/edit`}>Edit</Link><button className="button" disabled={publishing} onClick={publish}>{publishing ? 'Publishing…' : 'Publish program'}</button></div>}</div><div className="detail-grid"><div><dt>Publication status</dt><dd><span className={`status status-${program.publicationStatus.toLowerCase()}`}>{program.publicationStatus}</span></dd></div><div><dt>Intake status</dt><dd>{program.intakeStatus ?? 'Not available for drafts'}</dd></div><div><dt>Applications open</dt><dd>{date(program.applicationOpenAt)}</dd></div><div><dt>Applications close</dt><dd>{date(program.applicationCloseAt)}</dd></div></div><article className="content-card"><h2>Description</h2><p className="preserve-lines">{program.description}</p></article></>}</section>
}

function local(instant: string) { const d = new Date(instant); const offset = d.getTimezoneOffset(); return new Date(d.getTime() - offset * 60000).toISOString().slice(0, 16) }
export function AdminProgramFormPage({ edit = false }: { edit?: boolean }) {
  const { programId } = useParams(); const navigate = useNavigate(); const [version, setVersion] = useState(0); const [code, setCode] = useState(''); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [open, setOpen] = useState(''); const [close, setClose] = useState(''); const [error, setError] = useState<unknown>(); const [validation, setValidation] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { if (edit && programId) api.adminProgram(programId).then(p => { if (p.publicationStatus !== 'DRAFT') throw new Error('Published programs are read-only.'); setVersion(p.version); setCode(p.code); setTitle(p.title); setDescription(p.description); setOpen(local(p.applicationOpenAt)); setClose(local(p.applicationCloseAt)) }).catch(setError) }, [edit, programId])
  async function submit(e: FormEvent) { e.preventDefault(); setValidation(''); setError(undefined); if (!title.trim() || !description.trim() || !open || !close || (!edit && !/^[A-Za-z0-9][A-Za-z0-9_-]{1,49}$/.test(code.trim()))) return setValidation('Complete all fields with a valid 2–50 character program code.'); if (title.length > 255 || description.length > 4000 || new Date(open) >= new Date(close)) return setValidation('Check field lengths and ensure the opening time is before the closing time.'); setSaving(true); try { const times = { title: title.trim(), description: description.trim(), applicationOpenAt: new Date(open).toISOString(), applicationCloseAt: new Date(close).toISOString() }; const saved = edit && programId ? await api.updateAdminProgram(programId, { version, ...times }) : await api.createAdminProgram({ code: code.trim(), ...times }); navigate(`/admin/programs/${saved.id}`) } catch (e) { setError(e) } finally { setSaving(false) } }
  const formReady = !edit || code !== ''
  return <section className="page narrow"><Link to={programId ? `/admin/programs/${programId}` : '/admin/programs'}>← Cancel</Link><div className="page-heading"><div><p className="eyebrow">Administration</p><h1>{edit ? 'Edit program draft' : 'Create program draft'}</h1></div></div>{error !== undefined && <><ErrorNotice error={error}/>{error instanceof ApiError && error.status === 409 && programId && <Link to={`/admin/programs/${programId}`}>Return to the latest program</Link>}</>}{edit && !formReady && error === undefined && <div className="notice" role="status">Loading program draft…</div>}{validation && <div className="notice error" role="alert">{validation}</div>}{formReady && <form className="business-form" onSubmit={submit}>{edit ? <label>Program code<input value={code} disabled aria-describedby="immutable-code"/><small id="immutable-code">Program code cannot be changed.</small></label> : <label>Program code<input value={code} onChange={e => setCode(e.target.value)} maxLength={50} required/></label>}<label>Title<input value={title} onChange={e => setTitle(e.target.value)} maxLength={255} required/></label><label>Description<textarea value={description} onChange={e => setDescription(e.target.value)} maxLength={4000} required rows={8}/></label><div className="form-row"><label>Application opens<input type="datetime-local" value={open} onChange={e => setOpen(e.target.value)} required/></label><label>Application closes<input type="datetime-local" value={close} onChange={e => setClose(e.target.value)} required/></label></div><button className="button" disabled={saving}>{saving ? 'Saving…' : edit ? 'Save draft' : 'Create draft'}</button></form>}</section>
}

export function AdminUsersPage() { const [number,setNumber]=useState(0), [role,setRole]=useState<Role|''>(''); const [page,setPage]=useState<ApiPage<AdminUserSummary>>(); const [error,setError]=useState<unknown>(); useEffect(()=>{api.adminUsers(number,20,role||undefined).then(setPage).catch(setError)},[number,role]); return <section className="page"><h1>Users</h1><label className="filter">Role<select value={role} onChange={e=>{setRole(e.target.value as Role|'');setNumber(0)}}><option value="">All roles</option><option>APPLICANT</option><option>REVIEWER</option><option>ADMIN</option></select></label>{error!==undefined&&<ErrorNotice error={error}/>} {page&&<><div className="table-wrap"><table><thead><tr><th>Username</th><th>Display name</th><th>Email</th><th>Role</th><th>Created</th></tr></thead><tbody>{page.items.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.displayName}</td><td>{u.email}</td><td>{u.role}</td><td>{date(u.createdAt)}</td></tr>)}</tbody></table></div><PageNav page={page} setPage={setNumber}/></>}</section> }

export function AdminApplicationsPage() { const [number,setNumber]=useState(0),[status,setStatus]=useState<ApplicationStatus|''>('');const[page,setPage]=useState<ApiPage<AdminApplicationSummary>>();const[error,setError]=useState<unknown>();useEffect(()=>{api.adminApplications(number,20,status||undefined).then(setPage).catch(setError)},[number,status]);return <section className="page"><h1>Applications</h1><label className="filter">Status<select value={status} onChange={e=>{setStatus(e.target.value as ApplicationStatus|'');setNumber(0)}}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label>{error!==undefined&&<ErrorNotice error={error}/>} {page&&<><div className="table-wrap"><table><thead><tr><th>Program</th><th>Organization / project</th><th>Applicant</th><th>Reviewer</th><th>Amount</th><th>Status</th><th>Updated</th><th/></tr></thead><tbody>{page.items.map(a=><tr key={a.id}><td>{a.program.code}</td><td>{a.applicantOrganizationName}<br/><small>{a.projectTitle}</small></td><td>{a.applicant.displayName}</td><td>{a.reviewer?.displayName??'Unassigned'}</td><td>{formatMoney(a.requestedAmount)}</td><td><StatusBadge status={a.status}/></td><td>{date(a.updatedAt)}</td><td><Link to={`/admin/applications/${a.id}`}>Detail</Link></td></tr>)}</tbody></table></div><PageNav page={page} setPage={setNumber}/></>}</section> }

export function AdminApplicationDetailPage() { const {applicationId}=useParams();const[application,setApplication]=useState<AdminApplicationDetail>();const[history,setHistory]=useState<AdminHistoryItem[]>([]);const[error,setError]=useState<unknown>();useEffect(()=>{if(applicationId)Promise.all([api.adminApplication(applicationId),api.adminApplicationHistory(applicationId)]).then(([a,h])=>{setApplication(a);setHistory(h)}).catch(setError)},[applicationId]);return <section className="page"><Link to="/admin/applications">← Applications</Link>{error!==undefined&&<ErrorNotice error={error}/>} {application&&<><div className="page-heading"><div><p className="eyebrow">{application.program.code}</p><h1>{application.projectTitle}</h1><StatusBadge status={application.status}/></div></div><div className="detail-grid"><div><dt>Organization</dt><dd>{application.applicantOrganizationName}</dd></div><div><dt>Applicant</dt><dd>{application.applicant.displayName} ({application.applicant.username})</dd></div><div><dt>Reviewer</dt><dd>{application.reviewer?.displayName??'Unassigned'}</dd></div><div><dt>Requested amount</dt><dd>{formatMoney(application.requestedAmount)}</dd></div></div><article className="content-card"><h2>Short summary</h2><p>{application.shortSummary}</p><h2>Detailed plan</h2><p className="preserve-lines">{application.detailedPlan}</p></article><section><h2>Status history</h2>{history.length===0?<div className="notice">No history recorded.</div>:<ol className="history-list">{history.map(h=><li key={h.id}><strong>{h.fromStatus??'Created'} → {h.toStatus}</strong><span>{date(h.changedAt)} · {h.changedBy.displayName} ({h.changedBy.role})</span>{h.reason&&<p>{h.reason}</p>}</li>)}</ol>}</section></>}</section> }

function Subject({audit}:{audit:AdminAuditItem}) { const label=`${audit.subjectType} #${audit.subjectId}`; if(audit.subjectType==='APPLICATION')return <Link to={`/admin/applications/${audit.subjectId}`}>{label}</Link>;if(audit.subjectType==='PROGRAM')return <Link to={`/admin/programs/${audit.subjectId}`}>{label}</Link>;return <span>{label}</span> }
export function AdminAuditsPage() { const[number,setNumber]=useState(0),[event,setEvent]=useState<AuditEventType|''>('');const[page,setPage]=useState<ApiPage<AdminAuditItem>>();const[error,setError]=useState<unknown>();useEffect(()=>{api.adminAudits(number,50,event||undefined).then(setPage).catch(setError)},[number,event]);return <section className="page"><h1>Audit events</h1><label className="filter">Event type<select value={event} onChange={e=>{setEvent(e.target.value as AuditEventType|'');setNumber(0)}}><option value="">All event types</option>{events.map(e=><option key={e}>{e}</option>)}</select></label>{error!==undefined&&<ErrorNotice error={error}/>} {page&&<><div className="table-wrap"><table><thead><tr><th>Timestamp</th><th>Event type</th><th>Actor</th><th>Subject</th></tr></thead><tbody>{page.items.map(a=><tr key={a.id}><td>{date(a.occurredAt)}</td><td>{a.eventType}</td><td>{a.actor.displayName} ({a.actor.role})</td><td><Subject audit={a}/></td></tr>)}</tbody></table></div><PageNav page={page} setPage={setNumber}/></>}</section> }
