import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, ApiError } from '../api/client'
import { ErrorNotice } from '../components/ErrorNotice'
import { StatusBadge } from '../components/StatusBadge'
import type { ApplicationHistory, Attachment, ReviewerApplicationDetail } from '../types/api'
import { formatMoney, formatTimestamp } from './ApplicationsPage'

type PendingAction = 'start' | 'revision' | 'approve' | 'reject'

export function ReviewerApplicationPage() {
  const { applicationId } = useParams(); const navigate = useNavigate()
  const [application, setApplication] = useState<ReviewerApplicationDetail>(); const [history, setHistory] = useState<ApplicationHistory[]>([]); const [attachments, setAttachments] = useState<Attachment[]>([])
  const [error, setError] = useState<unknown>(); const [attachmentError, setAttachmentError] = useState<unknown>(); const [pending, setPending] = useState<PendingAction>(); const [decision, setDecision] = useState<'revision' | 'reject'>(); const [reasonError, setReasonError] = useState(''); const [claimConflict, setClaimConflict] = useState(false)
  const load = useCallback(async () => { if (!applicationId) return; setError(undefined); try { const [detail, changes, files] = await Promise.all([api.reviewerApplication(applicationId), api.reviewerHistory(applicationId), api.reviewerAttachments(applicationId)]); setApplication(detail); setHistory(changes); setAttachments(files) } catch (reason) { setError(reason) } }, [applicationId])
  useEffect(() => { void load() }, [load])
  async function start() { if (!applicationId || !application || pending) return; setPending('start'); setError(undefined); setClaimConflict(false); try { setApplication(await api.startReview(applicationId, application.version)) } catch (reason) { setError(reason); setClaimConflict(reason instanceof ApiError && (reason.status === 409 || reason.status === 422)) } finally { setPending(undefined) } }
  async function approve() { if (!applicationId || !application || pending) return; setPending('approve'); setError(undefined); setDecisionConflict(false); try { await api.approveApplication(applicationId, application.version); navigate('/review', { replace: true, state: { message: 'Application approved.' } }) } catch (reason) { setError(reason); setDecisionConflict(reason instanceof ApiError && (reason.status === 409 || reason.status === 422)) } finally { setPending(undefined) } }
  async function decide(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!applicationId || !application || !decision || pending) return; const reason = String(new FormData(event.currentTarget).get('reason') ?? '').trim(); if (!reason) { setReasonError('A reason is required.'); return } if (reason.length > 2000) { setReasonError('The reason must be 2,000 characters or fewer.'); return } setReasonError(''); setError(undefined); setDecisionConflict(false); setPending(decision); try { if (decision === 'revision') await api.requestRevision(applicationId, application.version, reason); else await api.rejectApplication(applicationId, application.version, reason); navigate('/review', { replace: true, state: { message: decision === 'revision' ? 'Revision requested.' : 'Application rejected.' } }) } catch (requestError) { setError(requestError); setDecisionConflict(requestError instanceof ApiError && (requestError.status === 409 || requestError.status === 422)) } finally { setPending(undefined) } }
  async function download(file: Attachment) { if (!applicationId) return; setAttachmentError(undefined); try { const result = await api.downloadReviewerAttachment(applicationId, file.id); const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = result.filename || file.filename; link.click(); URL.revokeObjectURL(url) } catch (reason) { setAttachmentError(reason) } }
  const busy = pending !== undefined
  return <section className="page detail-page reviewer-detail"><Link className="back-link" to="/review">← Review queue</Link>
    {!application && error === undefined && <div className="notice" role="status">Loading application for review…</div>}{error !== undefined && <ErrorNotice error={error}/>} {claimConflict && <div className="conflict-actions"><strong>This application is no longer available to start.</strong><span>Another reviewer may have claimed it first, or its status changed. The request was not retried.</span><Link className="button secondary" to="/review">Return to review queue</Link></div>} {decisionConflict && <div className="conflict-actions"><strong>This review changed before the decision completed.</strong><span>The decision was not retried. Return to the queue and reopen the current work before deciding again.</span><Link className="button secondary" to="/review">Return to review queue</Link></div>}
    {application && <><header className="detail-header"><div><span className="program-code">{application.program.code} · {application.program.title}</span><h1>{application.projectTitle}</h1></div><StatusBadge status={application.status}/></header>
      <section className="workflow-panel review-actions"><div><strong>Reviewer assignment</strong><p>{application.reviewer ? `${application.reviewer.displayName} (${application.reviewer.username})` : 'Unassigned — start review to claim this work.'}</p></div>{application.status === 'SUBMITTED' && <button className="button" disabled={busy} onClick={start}>{pending === 'start' ? 'Starting…' : 'Start review'}</button>}{application.status === 'IN_REVIEW' && <div className="action-row"><button className="button secondary" disabled={busy} onClick={() => { setDecision('revision'); setReasonError('') }}>Request revision</button><button className="button" disabled={busy} onClick={approve}>{pending === 'approve' ? 'Approving…' : 'Approve'}</button><button className="button danger" disabled={busy} onClick={() => { setDecision('reject'); setReasonError('') }}>Reject</button></div>}</section>
      {application.status === 'IN_REVIEW' && decision && <form className="decision-panel" onSubmit={decide}><h2>{decision === 'revision' ? 'Request revision' : 'Reject application'}</h2><p>{decision === 'revision' ? 'Explain the changes the applicant must make.' : 'Record a clear reason for rejection.'}</p><label>Reason<textarea name="reason" required maxLength={2000} rows={5} aria-describedby="reason-help"/></label><small id="reason-help">Required, up to 2,000 characters.</small>{reasonError && <div className="field-error" role="alert">{reasonError}</div>}<div className="action-row"><button type="button" className="button secondary" disabled={busy} onClick={() => setDecision(undefined)}>Cancel</button><button className={decision === 'reject' ? 'button danger' : 'button'} disabled={busy}>{busy ? 'Submitting…' : decision === 'revision' ? 'Send revision request' : 'Confirm rejection'}</button></div></form>}
      <section className="content-panel"><h2>Applicant</h2><dl className="information-grid"><div><dt>Display name</dt><dd>{application.applicant.displayName}</dd></div><div><dt>Username</dt><dd>{application.applicant.username}</dd></div><div><dt>Email</dt><dd>{application.applicant.email}</dd></div><div><dt>Organization</dt><dd>{application.applicantOrganizationName}</dd></div></dl></section>
      <section className="content-panel"><h2>Application</h2><dl className="information-grid"><div className="wide"><dt>Short summary</dt><dd>{application.shortSummary}</dd></div><div><dt>Requested amount</dt><dd>{formatMoney(application.requestedAmount)}</dd></div><div><dt>Created</dt><dd>{formatTimestamp(application.createdAt)}</dd></div><div><dt>Updated</dt><dd>{formatTimestamp(application.updatedAt)}</dd></div><div className="wide"><dt>Detailed plan</dt><dd>{application.detailedPlan}</dd></div></dl></section>
      <section className="content-panel"><h2>Attachments</h2>{attachmentError !== undefined && <ErrorNotice error={attachmentError}/>} {attachments.length === 0 ? <p className="muted">No attachments.</p> : <div className="attachment-list">{attachments.map((file) => <div key={file.id}><div><strong>{file.filename}</strong><small>{file.contentType} · {file.size === null ? 'Size pending' : formatBytes(file.size)} · {file.status} · {formatTimestamp(file.createdAt)}</small></div>{file.status === 'AVAILABLE' && <button className="text-button" onClick={() => download(file)}>Download</button>}</div>)}</div>}</section>
      <section className="content-panel"><h2>Status history</h2>{history.length === 0 ? <p className="muted">No status changes recorded.</p> : <ol className="timeline">{history.map((change) => <li key={change.id}><time>{formatTimestamp(change.changedAt)}</time><strong>{change.fromStatus ? `${change.fromStatus} → ` : ''}{change.toStatus}</strong>{change.reason && <p>{change.reason}</p>}</li>)}</ol>}</section></>}
  </section>
}
const formatBytes = (size: number) => size < 1024 ? `${size} B` : size < 1048576 ? `${(size / 1024).toFixed(1)} KB` : `${(size / 1048576).toFixed(1)} MB`
