import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, ApiError } from '../api/client'
import { ErrorNotice } from '../components/ErrorNotice'
import { StatusBadge } from '../components/StatusBadge'
import type { ApplicationHistory, Attachment, ReviewerApplicationDetail } from '../types/api'
import { formatMoney, formatTimestamp } from './ApplicationsPage'
import { applicationStatusLabel, attachmentStatusLabels } from '../utils/presentation'

type PendingAction = 'start' | 'revision' | 'approve' | 'reject'

export function ReviewerApplicationPage() {
  const { applicationId } = useParams(); const navigate = useNavigate()
  const [application, setApplication] = useState<ReviewerApplicationDetail>(); const [history, setHistory] = useState<ApplicationHistory[]>([]); const [attachments, setAttachments] = useState<Attachment[]>([])
  const [error, setError] = useState<unknown>(); const [attachmentError, setAttachmentError] = useState<unknown>(); const [pending, setPending] = useState<PendingAction>(); const [decision, setDecision] = useState<'revision' | 'reject'>(); const [reasonError, setReasonError] = useState(''); const [claimConflict, setClaimConflict] = useState(false); const [decisionConflict, setDecisionConflict] = useState(false)
  const load = useCallback(async () => { if (!applicationId) return; setError(undefined); try { const [detail, changes, files] = await Promise.all([api.reviewerApplication(applicationId), api.reviewerHistory(applicationId), api.reviewerAttachments(applicationId)]); setApplication(detail); setHistory(changes); setAttachments(files) } catch (reason) { setError(reason) } }, [applicationId])
  useEffect(() => { void load() }, [load])
  async function start() { if (!applicationId || !application || pending) return; setPending('start'); setError(undefined); setClaimConflict(false); try { setApplication(await api.startReview(applicationId, application.version)) } catch (reason) { setError(reason); setClaimConflict(reason instanceof ApiError && (reason.status === 409 || reason.status === 422)) } finally { setPending(undefined) } }
  async function approve() { if (!applicationId || !application || pending) return; setPending('approve'); setError(undefined); setDecisionConflict(false); try { await api.approveApplication(applicationId, application.version); navigate('/review', { replace: true, state: { message: '신청을 승인했습니다.' } }) } catch (reason) { setError(reason); setDecisionConflict(reason instanceof ApiError && (reason.status === 409 || reason.status === 422)) } finally { setPending(undefined) } }
  async function decide(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!applicationId || !application || !decision || pending) return; const reason = String(new FormData(event.currentTarget).get('reason') ?? '').trim(); if (!reason) { setReasonError('사유를 입력해 주세요.'); return } if (reason.length > 2000) { setReasonError('사유는 2,000자 이내로 입력해 주세요.'); return } setReasonError(''); setError(undefined); setDecisionConflict(false); setPending(decision); try { if (decision === 'revision') await api.requestRevision(applicationId, application.version, reason); else await api.rejectApplication(applicationId, application.version, reason); navigate('/review', { replace: true, state: { message: decision === 'revision' ? '보완을 요청했습니다.' : '신청을 반려했습니다.' } }) } catch (requestError) { setError(requestError); setDecisionConflict(requestError instanceof ApiError && (requestError.status === 409 || requestError.status === 422)) } finally { setPending(undefined) } }
  async function download(file: Attachment) { if (!applicationId) return; setAttachmentError(undefined); try { const result = await api.downloadReviewerAttachment(applicationId, file.id); const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = result.filename || file.filename; link.click(); URL.revokeObjectURL(url) } catch (reason) { setAttachmentError(reason) } }
  const busy = pending !== undefined
  return <section className="page detail-page reviewer-detail"><Link className="back-link" to="/review">← 심사 업무</Link>
    {!application && error === undefined && <div className="notice" role="status">심사할 신청서를 불러오는 중…</div>}{error !== undefined && <ErrorNotice error={error}/>} {claimConflict && <div className="conflict-actions"><strong>이 신청서는 더 이상 심사를 시작할 수 없습니다.</strong><span>다른 심사자가 먼저 배정되었거나 상태가 변경되었습니다. 요청을 자동 재시도하지 않았습니다.</span><Link className="button secondary" to="/review">심사 목록으로 돌아가기</Link></div>} {decisionConflict && <div className="conflict-actions"><strong>처리 중 심사 정보가 변경되었습니다.</strong><span>결정을 자동 재시도하지 않았습니다. 목록에서 최신 신청서를 다시 열어 처리해 주세요.</span><Link className="button secondary" to="/review">심사 목록으로 돌아가기</Link></div>}
    {application && <><header className="detail-header"><div><span className="program-code">{application.program.code} · {application.program.title}</span><h1>{application.projectTitle}</h1></div><StatusBadge status={application.status}/></header>
      <section className="workflow-panel review-actions"><div><strong>담당 심사자</strong><p>{application.reviewer ? `${application.reviewer.displayName} (${application.reviewer.username})` : '미배정 — 심사를 시작하면 담당자로 배정됩니다.'}</p></div>{application.status === 'SUBMITTED' && <button className="button" disabled={busy} onClick={start}>{pending === 'start' ? '시작 중…' : '심사 시작'}</button>}{application.status === 'IN_REVIEW' && <div className="action-row"><button className="button secondary" disabled={busy} onClick={() => { setDecision('revision'); setReasonError('') }}>보완 요청</button><button className="button" disabled={busy} onClick={approve}>{pending === 'approve' ? '승인 중…' : '승인'}</button><button className="button danger" disabled={busy} onClick={() => { setDecision('reject'); setReasonError('') }}>반려</button></div>}</section>
      {application.status === 'IN_REVIEW' && decision && <form className="decision-panel" onSubmit={decide}><h2>{decision === 'revision' ? '보완 요청' : '신청 반려'}</h2><p>{decision === 'revision' ? '신청자가 수정해야 할 내용을 구체적으로 안내하세요.' : '반려 사유를 명확하게 기록하세요.'}</p><label>처리 사유<textarea name="reason" required maxLength={2000} rows={5} aria-describedby="reason-help"/></label><small id="reason-help">필수 입력 항목이며 2,000자까지 작성할 수 있습니다.</small>{reasonError && <div className="field-error" role="alert">{reasonError}</div>}<div className="action-row"><button type="button" className="button secondary" disabled={busy} onClick={() => setDecision(undefined)}>취소</button><button className={decision === 'reject' ? 'button danger' : 'button'} disabled={busy}>{busy ? '처리 중…' : decision === 'revision' ? '보완 요청 보내기' : '반려 확정'}</button></div></form>}
      <section className="content-panel"><h2>신청자 정보</h2><dl className="information-grid"><div><dt>이름</dt><dd>{application.applicant.displayName}</dd></div><div><dt>아이디</dt><dd>{application.applicant.username}</dd></div><div><dt>이메일</dt><dd>{application.applicant.email}</dd></div><div><dt>신청 기관</dt><dd>{application.applicantOrganizationName}</dd></div></dl></section>
      <section className="content-panel"><h2>신청 내용</h2><dl className="information-grid"><div className="wide"><dt>요약</dt><dd>{application.shortSummary}</dd></div><div><dt>신청 금액</dt><dd>{formatMoney(application.requestedAmount)}</dd></div><div><dt>작성일</dt><dd>{formatTimestamp(application.createdAt)}</dd></div><div><dt>수정일</dt><dd>{formatTimestamp(application.updatedAt)}</dd></div><div className="wide"><dt>세부 계획</dt><dd>{application.detailedPlan}</dd></div></dl></section>
      <section className="content-panel"><h2>첨부 파일</h2>{attachmentError !== undefined && <ErrorNotice error={attachmentError}/>} {attachments.length === 0 ? <p className="muted">첨부 파일이 없습니다.</p> : <div className="attachment-list">{attachments.map((file) => <div key={file.id}><div><strong>{file.filename}</strong><small>{file.contentType} · {file.size === null ? '크기 확인 중' : formatBytes(file.size)} · {file.status} · {formatTimestamp(file.createdAt)}</small></div>{file.status === 'AVAILABLE' && <button className="text-button" onClick={() => download(file)}>다운로드</button>}</div>)}</div>}</section>
      <section className="content-panel"><h2>진행 이력</h2>{history.length === 0 ? <p className="muted">기록된 진행 이력이 없습니다.</p> : <ol className="timeline">{history.map((change) => <li key={change.id}><time>{formatTimestamp(change.changedAt)}</time><strong>{change.fromStatus ? `${applicationStatusLabel(change.fromStatus)} → ` : ''}{applicationStatusLabel(change.toStatus)}</strong>{change.reason && <p>{change.reason}</p>}</li>)}</ol>}</section></>}
  </section>
}
const formatBytes = (size: number) => size < 1024 ? `${size} B` : size < 1048576 ? `${(size / 1024).toFixed(1)} KB` : `${(size / 1048576).toFixed(1)} MB`
