import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { clearCsrfTokenForTests } from '../api/client'
import { ReviewerApplicationPage } from './ReviewerApplicationPage'

const detail = (status = 'SUBMITTED', version = 3) => ({ id: 7, program: { id: 1, code: 'GRANT-1', title: 'Growth Grant' }, applicant: { id: 2, username: 'applicant', displayName: 'Applicant Person', email: 'applicant@example.test' }, reviewer: status === 'IN_REVIEW' ? { id: 3, username: 'reviewer', displayName: 'Review Person' } : null, applicantOrganizationName: 'Synthetic Works', projectTitle: 'Expansion', shortSummary: 'Grow operations', requestedAmount: 5000, detailedPlan: 'A careful synthetic plan', status, version, createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-02T00:00:00Z' })
const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }))
function mock(status = 'SUBMITTED', command?: (url: string, init?: RequestInit) => Promise<Response>) { return vi.fn((url: string, init?: RequestInit) => { if (url === '/api/v1/auth/csrf') return json({ headerName: 'X-CSRF-TOKEN', parameterName: '_csrf', token: 'token' }); if (init?.method === 'POST') return command!(url, init); if (url.endsWith('/history')) return json([{ id: 1, changedAt: '2026-01-02T00:00:00Z', fromStatus: 'IN_REVIEW', toStatus: 'NEEDS_REVISION', reason: 'Add a signed budget' }]); if (url.endsWith('/attachments')) return json([{ id: 9, filename: 'budget.pdf', contentType: 'application/pdf', size: 2048, status: 'AVAILABLE', createdAt: '2026-01-02T00:00:00Z' }]); return json(detail(status)) }) }
function view() { return render(<MemoryRouter initialEntries={['/review/applications/7']}><Routes><Route path="/review/applications/:applicationId" element={<ReviewerApplicationPage/>}/><Route path="/review" element={<h1>Queue destination</h1>}/></Routes></MemoryRouter>) }
afterEach(() => { cleanup(); clearCsrfTokenForTests(); vi.unstubAllGlobals(); vi.restoreAllMocks() })

describe('ReviewerApplicationPage', () => {
  it('shows application, read-only attachments, history reason, and download', async () => { const fetch = mock(); vi.stubGlobal('fetch', fetch); const create = vi.fn(() => 'blob:test'); const revoke = vi.fn(); Object.defineProperties(URL, { createObjectURL: { configurable: true, value: create }, revokeObjectURL: { configurable: true, value: revoke } }); view(); expect(await screen.findByRole('button', { name: 'Start review' })).toBeInTheDocument(); expect(screen.getByText('Applicant Person')).toBeInTheDocument(); expect(screen.getByText('Add a signed budget')).toBeInTheDocument(); expect(screen.getByText('budget.pdf')).toBeInTheDocument(); expect(screen.queryByText(/upload/i)).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: /delete/i })).not.toBeInTheDocument(); fetch.mockImplementationOnce(() => Promise.resolve(new Response(new Blob(['pdf']), { status: 200, headers: { 'Content-Disposition': 'attachment; filename="budget.pdf"' } }))); fireEvent.click(screen.getByRole('button', { name: 'Download' })); await waitFor(() => expect(create).toHaveBeenCalled()); expect(revoke).toHaveBeenCalledWith('blob:test') })
  it('starts with the current version and renders the returned IN_REVIEW actions', async () => { const command = vi.fn((_url: string, init?: RequestInit) => { expect(JSON.parse(String(init?.body))).toEqual({ version: 3 }); return json(detail('IN_REVIEW', 4)) }); vi.stubGlobal('fetch', mock('SUBMITTED', command)); view(); fireEvent.click(await screen.findByRole('button', { name: 'Start review' })); expect(await screen.findByText('In review')).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Approve' })).toBeInTheDocument(); expect(command).toHaveBeenCalledTimes(1) })
  it.each([409, 422])('treats a %s claim race as a non-retried queue recovery case', async (status) => { const command = vi.fn(() => json({ title: 'Conflict', status, detail: 'Application unavailable' }, status)); vi.stubGlobal('fetch', mock('SUBMITTED', command)); view(); fireEvent.click(await screen.findByRole('button', { name: 'Start review' })); expect(await screen.findByText(/Another reviewer may have claimed it first/)).toBeInTheDocument(); expect(screen.getByRole('link', { name: 'Return to review queue' })).toBeInTheDocument(); expect(command).toHaveBeenCalledTimes(1) })
  it.each([['Request revision', 'Send revision request'], ['Reject', 'Confirm rejection']])('requires a reason before %s', async (open, submit) => { const command = vi.fn(); vi.stubGlobal('fetch', mock('IN_REVIEW', command)); view(); fireEvent.click(await screen.findByRole('button', { name: open })); fireEvent.submit(screen.getByRole('button', { name: submit }).closest('form')!); expect(await screen.findByText('A reason is required.')).toBeInTheDocument(); expect(command).not.toHaveBeenCalled() })
  it.each([['Request revision', 'Send revision request', '/request-revision', 'Revision requested.'], ['Reject', 'Confirm rejection', '/reject', 'Application rejected.']])('submits %s with a reason and returns to the queue', async (open, submit, endpoint, _message) => { const command = vi.fn((url: string, init?: RequestInit) => { expect(url).toContain(endpoint); expect(JSON.parse(String(init?.body))).toEqual({ version: 3, reason: 'Clear reason' }); return json(detail()) }); vi.stubGlobal('fetch', mock('IN_REVIEW', command)); view(); fireEvent.click(await screen.findByRole('button', { name: open })); fireEvent.change(screen.getByLabelText('Reason'), { target: { value: '  Clear reason  ' } }); fireEvent.click(screen.getByRole('button', { name: submit })); expect(await screen.findByRole('heading', { name: 'Queue destination' })).toBeInTheDocument(); expect(command).toHaveBeenCalledTimes(1) })
  it('approves with version only and returns directly to the queue', async () => { const command = vi.fn((_url: string, init?: RequestInit) => { expect(JSON.parse(String(init?.body))).toEqual({ version: 3 }); return json(detail()) }); vi.stubGlobal('fetch', mock('IN_REVIEW', command)); view(); fireEvent.click(await screen.findByRole('button', { name: 'Approve' })); expect(await screen.findByRole('heading', { name: 'Queue destination' })).toBeInTheDocument(); expect(command).toHaveBeenCalledTimes(1) })
})
